version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  mysql-server:
    container_name: mysql-server
    image: mariadb:jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ../..:/workspaces:cached
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
